"""
Constants/settings for the game.
"""
import os

# COLORS
SLATE_GRAY = (46, 46, 54)

# PATHS
ASSET_ROOT = os.path.join("assets")
CARD_ROOT = os.path.join(ASSET_ROOT, "cards")

# WINDOW
WINWIDTH = 800
WINHEIGHT = 500
CENTRE = (WINWIDTH // 2, WINHEIGHT // 2)
WINTITLE = "Cryptids TGC"

# FRAME RATES
CLOCKSPEED = 30


# APPEARANCE
FONT = 'freesansbold.ttf'


# GAME STATUS
GAME_STATUSES = ["intro", "home_screen", "duel"]
DEFAULT_STATUS = "intro"

# % INTRO
TITLE_DURATION = 3  # secs
TITLE_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
TITLE_SCREEN_TEXT = "CRYPTIDS"
TITLE_SCREEN_FONT = 'freesansbold.ttf'
TITLE_SCREEN_FONT_SIZE = 32
TITLE_SCREEN_TEXT_COLOUR = "Black"
# CREDIT
CREDIT_DURATION = 3  # secs
CREDIT_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
CREDIT_SCREEN_TEXT = "made by Jamie Bright"
CREDIT_SCREEN_FONT = 'freesansbold.ttf'
CREDIT_SCREEN_FONT_SIZE = 32
CREDIT_SCREEN_TEXT_COLOUR = "Black"
# LOGO
LOGO_DURATION = 3  # secs
LOGO_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
LOGO_SCREEN_IMAGE_PATH = os.path.join(ASSET_ROOT, "logo.png")
LOGO_HEIGHT_RELATIVE_TO_SCREEN_HEIGHT = 0.7
# HOME
HOME_SCREEN_FONT = 'freesansbold.ttf'
HOME_SCREEN_FONT_SIZE = 32
HOME_SCREEN_TEXT_COLOUR = "Black"
HOME_BUTTON_X_REL = 0.2
HOME_BUTTON_Y_REL = 0.33
