"""Constants/settings for the game."""
import os

DEVELOPER = "Waimanu"
VERBOSE = True
DEFAULT_USERNAME = "default"
DEFAULT_PASSWORD = "Password123"

# COLORS
SLATE_GRAY = (56, 56, 64)
PALE_SLATE_GRAY = (76, 76, 84)
SLATE_GRAY_TRANSPARENT = (56, 56, 64, 128)
RED = "Red"
BLACK = "Black"
PINK = "Pink"
ORANGE = "Orange"
GREEN = "Green"
WHITE = "White"
BLUE = "Blue"
PALE_GREEN = (215, 236, 215)

# PATHS
ASSET_ROOT = os.path.join("assets")
CARD_ROOT = os.path.join(ASSET_ROOT, "cards")

# WINDOW
WINWIDTH = 800
WINHEIGHT = 500
X25 = WINWIDTH // 4
X50 = WINWIDTH // 2
X75 = X25 * 3
Y75 = WINHEIGHT // 4
Y50 = WINHEIGHT // 2
Y25 = Y75 * 3
CENTRE = (X50, Y50)
WINTITLE = "Cryptids TGC"

# FRAME RATES
CLOCKSPEED = 60

# APPEARANCE
FONT = os.path.join("assets", "fonts", "Cabin_Sketch", "CabinSketch-Regular.ttf")

# BUTTON DEFAULTS
DEFAULT_BUTTON_DELAY_ON_CLICK = 0.4  # seconds
BUTTON_DEFAULT_FONTNAME = FONT
BUTTON_DEFAULT_FONTSIZE = 32
BUTTON_DEFAULT_FONTCOLOUR = BLACK
BUTTON_DEFAULT_BGCOLOUR = WHITE
BUTTON_DEFAULT_BACKGROUND_HIGHLIGHTED = PINK
BUTTON_DEFAULT_HEIGHT = WINHEIGHT // 15
BUTTON_DEFAULT_WIDTH = 140
BUTTON_DEFAULT_BORDER_COLOUR = BLACK
BUTTON_DEFAULT_BORDER_THICKNESS = 5
BUTTON_DEFAULT_BORDER_HIGHLIGHTED = PINK
BUTTON_DEFAULT_BACKGROUND_CLICKED = GREEN
BUTTON_DEFAULT_TOGGLE_HOVER_BG_COLOUR = ORANGE
BUTTON_DEFAULT_TOGGLED_BG_COLOUR = BLUE
BUTTON_DEFAULT_TEXT_X_BUFFER = 10
BUTTON_DEFAULT_TEXT_Y_BUFFER = 10
BUTTON_DEFAULT_BACKGROUND_DISABLED = PALE_SLATE_GRAY

BUTTON_INPUTTEXT_FONTCOLOUR = RED
BUTTON_INTPUTTEXT_BACKGROUND_COLOUR = BLACK
BUTTON_ACTIVE_BACKGROUND_COLOUR = WHITE
BUTTON_ACTIVE_TEXT_COLOUR = BLACK
BUTTON_INTPUTTEXT_FONTNAME = FONT
BUTTON_INTPUTTEXT_FONTSIZE = 32
BUTTON_INTPUTTEXT_BORDER_COLOUR = WHITE


# GAME STATUS
DEFAULT_STATUS = "intro"
STATUS_INTRO = "intro"
STATUS_HOME = "home"
STATUS_SETTINGS = "settings"
STATUS_PREPLAY = "play"
STATUS_OUTRO = "outro"
STATUS_GAMEPLAY = "gameplay"
STATUS_PAUSE = "pause"
STATUS_POPUP = "popup"
GAME_STATUSES = [STATUS_INTRO, STATUS_HOME, STATUS_SETTINGS, STATUS_PREPLAY, STATUS_OUTRO, STATUS_GAMEPLAY, STATUS_PAUSE, STATUS_POPUP]

# TITLE SCREEN
TITLE_DURATION = 1  # secs
TITLE_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
TITLE_SCREEN_TEXT = "CRYPTIDS"
TITLE_SCREEN_FONT = FONT
TITLE_SCREEN_FONT_SIZE = 90
TITLE_SCREEN_TEXT_COLOUR = BLACK

# CREDIT SCREEN
CREDIT_DURATION = 1  # secs
CREDIT_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
CREDIT_SCREEN_TEXT = f"designed and developed by {DEVELOPER}"
CREDIT_SCREEN_FONT = FONT
CREDIT_SCREEN_FONT_SIZE = 32
CREDIT_SCREEN_TEXT_COLOUR = BLACK

# LOGO SCREEN
LOGO_DURATION = 1  # secs
LOGO_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
LOGO_SCREEN_IMAGE_PATH = os.path.join(ASSET_ROOT, "logo.png")
LOGO_HEIGHT_RELATIVE_TO_SCREEN_HEIGHT = 0.6


# OUTRO SCREEN
OUTRO_DURATION = 1  # secs
OUTRO_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
OUTRO_SCREEN_TEXT1 = "Thanks for playing"
OUTRO_SCREEN_TEXT2 = "CRYPTIDS"
OUTRO_SCREEN_TEXT3 = f"designed and developed by {DEVELOPER}"
OUTRO_SCREEN_FONT = FONT
OUTRO_SCREEN_FONT_SIZE1 = 32
OUTRO_SCREEN_FONT_SIZE2 = 90
OUTRO_SCREEN_FONT_SIZE3 = 32
OUTRO_SCREEN_TEXT_COLOUR = BLACK

# HOME SCREEN
HOME_SCREEN_FONT = FONT
HOME_SCREEN_FONT_SIZE = 32
HOME_SCREEN_TEXT_COLOUR = BLACK
HOME_BUTTON_X_REL = 0.2
HOME_BUTTON_Y_REL = 0.1

# SETTINGS SCREEN
SETTINGS_SCREEN_FONT = FONT
SETTINGS_SCREEN_FONT_SIZE = 32
SETTINGS_SCREEN_TEXT_COLOUR = BLACK
SETTINGS_BUTTON_X_REL = 0.2
SETTINGS_BUTTON_Y_REL = 0.1
SETTINGS_LOGO_IMG_ALPHA = 70

# KEYBINDS
K_BACK = ["backspace"]
K_ESC = ["esc"]
K_UP = ["up"]
K_DOWN = ["down"]
K_LEFT = ["left"]
K_RIGHT = ["right"]

# PAUSE MENU
PAUSE_MENU_BACKGROUND_COLOUR = SLATE_GRAY
PAUSE_MENU_BACKGROUND_TRANSPARENCY = 128
PAUSE_MENU_SCALE = 0.8
PAUSE_WINWIDTH = int(WINWIDTH * PAUSE_MENU_SCALE)
PAUSE_WINHEIGHT = int(WINHEIGHT * PAUSE_MENU_SCALE)
PAUSE_X25 = PAUSE_WINWIDTH // 4
PAUSE_X50 = PAUSE_WINWIDTH // 2
PAUSE_X75 = X25 * 3
PAUSE_Y75 = PAUSE_WINHEIGHT // 4
PAUSE_Y50 = PAUSE_WINHEIGHT // 2
PAUSE_Y25 = Y75 * 3
PAUSE_SCREEN_PAUSE_TEXT_COLOUR = RED
PAUSE_SCREEN_PAUSE_TEXT_FONTSIZE = 94
PAUSE_SCREEN_PAUSE_TEXT_FONT = FONT
PAUSE_CENTRE = (PAUSE_X50, PAUSE_Y50)

# POPUP MENU
POPUP_MENU_BACKGROUND_COLOUR = BLACK
POPUP_MENU_BACKGROUND_TRANSPARENCY = 250
POPUP_MENU_SCALE = 0.9
POPUP_WINWIDTH = int(WINWIDTH * POPUP_MENU_SCALE)
POPUP_WINHEIGHT = int(WINHEIGHT * POPUP_MENU_SCALE)
POPUP_X25 = POPUP_WINWIDTH // 4
POPUP_X50 = POPUP_WINWIDTH // 2
POPUP_X75 = X25 * 3
POPUP_Y75 = POPUP_WINHEIGHT // 4
POPUP_Y50 = POPUP_WINHEIGHT // 2
POPUP_Y25 = Y75 * 3
POPUP_SCREEN_POPUP_HEADING_COLOUR = RED
POPUP_SCREEN_POPUP_HEADING_FONTSIZE = 50
POPUP_SCREEN_POPUP_BODY_COLOUR = WHITE
POPUP_SCREEN_POPUP_BODY_FONTSIZE = 26
POPUP_SCREEN_POPUP_HEADING_FONT = FONT
POPUP_SCREEN_POPUP_BODY_FONT = FONT
POPUP_CENTRE = (POPUP_X50, POPUP_Y50)
POPUP_BODY_TEXT_OFFSET = int(POPUP_WINWIDTH * 0.1)
POPUP_HEADING_Y = int(POPUP_WINHEIGHT * 0.075)

# PREPLAY SCREEN
PREPLAY_LOGIN_TEXT_FONT = FONT
PREPLAY_LOGIN_TEXT_FONTSIZE = 36
PREPLAY_LOGIN_TEXT_COLOUR = RED
PREPLAY_LOGIN_TEXT_BGCOLOUR = WHITE
PREPLAY_USERNAME_PASSWORD_TEXT_COLOUR = WHITE


# GAME STYLING
GAME_FONT = FONT
GAME_FONT_COLOUR = BLACK
GAME_FONT_SIZE = 32

# PLAYER SETTINGS
STARTING_HP = 10000
DECK_SIZE = 100
HAND_SIZE = 5
FIELD_SIZE = 5

# TURN SETTINGS
CARDS_PER_TURN = 2

# GAME BOARD
GAME_BOARD_BACKGROUND_COLOUR = SLATE_GRAY
GRID_BORDER_THICKNESS = 10
GRID_BORDER_DEFAULT_COLOUR = RED

# CARD SETTINGS
CARD_ASPECT_RATIO_WH = (4, 7)  # width, height
