"""
Constants/settings for the game.
"""
import os

DEVELOPER = "Jamie"

# COLORS
SLATE_GRAY = (56, 56, 64)

# PATHS
ASSET_ROOT = os.path.join("assets")
CARD_ROOT = os.path.join(ASSET_ROOT, "cards")

# WINDOW
WINWIDTH = 800
WINHEIGHT = 500
X25 = WINWIDTH // 4
X50 = WINWIDTH // 2
X75 = X25 * 3
Y75 = WINHEIGHT // 4
Y50 = WINHEIGHT // 2
Y25 = Y75 * 3
CENTRE = (X50, Y50)
WINTITLE = "Cryptids TGC"

# FRAME RATES
CLOCKSPEED = 30


# APPEARANCE
FONT = os.path.join("assets", "fonts", "Cabin_Sketch", "CabinSketch-Regular.ttf")

# BUTTON DEFAULTS
DEFAULT_BUTTON_DELAY_ON_CLICK = 1  # seconds
BUTTON_DEFAULT_FONTNAME = FONT
BUTTON_DEFAULT_FONTSIZE = 32
BUTTON_DEFAULT_FONTCOLOUR = "Black"
BUTTON_DEFAULT_BGCOLOUR = "White"
BUTTON_DEFAULT_BACKGROUND_HIGHLIGHTED = "Pink"
BUTTON_DEFAULT_HEIGHT = WINHEIGHT // 15
BUTTON_DEFAULT_WIDTH = WINWIDTH // 10
BUTTON_DEFAULT_BORDER_COLOUR = "Black"
BUTTON_DEFAULT_BORDER_THICKNESS = 5
BUTTON_DEFAULT_BORDER_HIGHLIGHTED = "Pink"
BUTTON_DEFAULT_BACKGROUND_CLICKED = "Green"
BUTTON_DEFAULT_TOGGLE_HOVER_BG_COLOUR = "Orange"
BUTTON_DEFAULT_TOGGLED_BG_COLOUR = "Blue"

# GAME STATUS
STATUS_INTRO = "intro"
STATUS_HOME = "home"
STATUS_SETTINGS = "settings"
STATUS_PLAY = "play"
STATUS_OUTRO = "outro"
GAME_STATUSES = [STATUS_INTRO, STATUS_HOME, STATUS_SETTINGS, STATUS_PLAY, STATUS_OUTRO]
DEFAULT_STATUS = STATUS_INTRO

# TITLE SCREEN
TITLE_DURATION = 1  # secs
TITLE_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
TITLE_SCREEN_TEXT = "CRYPTIDS"
TITLE_SCREEN_FONT = FONT
TITLE_SCREEN_FONT_SIZE = 90
TITLE_SCREEN_TEXT_COLOUR = "Black"

# CREDIT SCREEN
CREDIT_DURATION = 1  # secs
CREDIT_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
CREDIT_SCREEN_TEXT = f"designed and developed by {DEVELOPER}"
CREDIT_SCREEN_FONT = FONT
CREDIT_SCREEN_FONT_SIZE = 32
CREDIT_SCREEN_TEXT_COLOUR = "Black"

# LOGO SCREEN
LOGO_DURATION = 1  # secs
LOGO_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
LOGO_SCREEN_IMAGE_PATH = os.path.join(ASSET_ROOT, "logo.png")
LOGO_HEIGHT_RELATIVE_TO_SCREEN_HEIGHT = 0.7


# OUTRO SCREEN
OUTRO_DURATION = 1  # secs
OUTRO_SCREEN_BACKGROUND_COLOR = SLATE_GRAY
OUTRO_SCREEN_TEXT1 = "Thanks for playing"
OUTRO_SCREEN_TEXT2 = "CRYPTIDS"
OUTRO_SCREEN_TEXT3 = f"designed and developed by {DEVELOPER}"
OUTRO_SCREEN_FONT = FONT
OUTRO_SCREEN_FONT_SIZE1 = 32
OUTRO_SCREEN_FONT_SIZE2 = 90
OUTRO_SCREEN_FONT_SIZE3 = 32
OUTRO_SCREEN_TEXT_COLOUR = "Black"

# HOME SCREEN
HOME_SCREEN_FONT = FONT
HOME_SCREEN_FONT_SIZE = 32
HOME_SCREEN_TEXT_COLOUR = "Black"
HOME_BUTTON_X_REL = 0.2
HOME_BUTTON_Y_REL = 0.1

# SETTINGS SCREEN
SETTINGS_SCREEN_FONT = FONT
SETTINGS_SCREEN_FONT_SIZE = 32
SETTINGS_SCREEN_TEXT_COLOUR = "Black"
SETTINGS_BUTTON_X_REL = 0.2
SETTINGS_BUTTON_Y_REL = 0.1
SETTINGS_LOGO_IMG_ALPHA = 70
